name: ci

on:
  push:
    branches:
      - 'master'
env:
  REGISTRY: docker.io
  IMAGE_NAME: mc-server-status

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version:
            18
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,json,ts}
          only_changed: True${{ env.IMAGE_NAME }}:${{ github.sha }}
