name: ci

on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version:
            18
      - run: npm ci
      - run: npm run prettier:check
      - run: npm test
      - run: npm run build --if-present
